# Generated by Django 6.0.2 on 2026-04-08 02:24

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('BEES', 'Abejas'), ('DOGS', 'Perros'), ('CATS', 'Gatos'), ('RABBITS', 'Conejos'), ('HORSES', 'Caballos'), ('BOVINES', 'Bovinos'), ('PORCINES', 'Porcinos'), ('OTHER', 'Otro (Sujeto a aprobación)')], default='BEES', max_length=20)),
                ('other_species', models.CharField(blank=True, help_text="Especificar si eligió 'Otro'", max_length=100, null=True)),
                ('description', models.TextField(help_text='Breve descripción de la situación')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(help_text='Dirección sugerida o detectada', max_length=255)),
                ('phone', models.CharField(help_text='Teléfono de contacto para el rescate', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pendiente de Aprobación'), ('PENDING_RESCUE', 'Pendiente de Rescate'), ('SCHEDULED', 'Programado'), ('RESCUED', 'Rescatado'), ('CANCELLED', 'Cancelado')], default='PENDING_APPROVAL', max_length=20)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescue_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Rescate',
                'verbose_name_plural': 'Solicitudes de Rescate',
                'ordering': ['-created_at'],
            },
        ),
    ]
