# Generated by Django 6.0.2 on 2026-04-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescuerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='¿Debe recibir notificaciones?')),
            ],
            options={
                'verbose_name': 'Contacto de Rescatista',
                'verbose_name_plural': 'Lista de Rescatistas (Notificaciones)',
            },
        ),
        migrations.AddField(
            model_name='rescuerequest',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo de contacto para el rescate', max_length=254, null=True),
        ),
    ]
