# Generated by Django 6.0.2 on 2026-04-08 03:47

import cloudinary.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('activity_type', models.CharField(choices=[('TOUR', 'Recorrido / Visita'), ('WORKSHOP', 'Taller'), ('EVENT', 'Evento Especial')], default='TOUR', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(help_text='Ej: 2 horas, Medio día', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio por persona', max_digits=10)),
                ('capacity', models.PositiveIntegerField(help_text='Cupo máximo')),
                ('remaining_capacity', models.PositiveIntegerField()),
                ('location', models.CharField(default='Rancho Tierra Viva', max_length=255)),
                ('image', cloudinary.models.CloudinaryField(help_text='Imagen principal', max_length=255, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='activities.activity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PAID', 'Pagado / Confirmado'), ('CANCELLED', 'Cancelado'), ('REFUNDED', 'Reembolsado')], default='PENDING', max_length=20)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
