# Generated by Django 6.0.2 on 2026-02-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('HIVE', 'Bee Hive'), ('SHEEP', 'Sheep'), ('GOAT', 'Goat'), ('COW', 'Cow'), ('HORSE', 'Horse'), ('CHICKEN', 'Chicken')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('is_available_for_sponsorship', models.BooleanField(default=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
            ],
        ),
    ]
