# Generated by Django 6.0.2 on 2026-03-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('HIVE', 'Bee Hive'), ('SHEEP', 'Sheep'), ('GOAT', 'Goat'), ('COW', 'Cow'), ('HORSE', 'Horse'), ('CHICKEN', 'Chicken'), ('RABBIT', 'Rabbit'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
