# Generated by Django 6.0.2 on 2026-04-05 16:33

import cloudinary.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_breed_species_remove_animal_type_animal_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='rescue_video_url',
            field=models.URLField(blank=True, help_text='Link a video de YouTube/Vimeo del rescate', null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='AnimalContentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_tier_level', models.IntegerField(default=0, help_text='Nivel mínimo de membresía para acceder (0 = público)')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, help_text='Dejar vacío para contenido general del Rancho', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalContentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Imagen'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='animals.animalcontentfolder')),
            ],
        ),
    ]
