# Generated by Django 6.0.2 on 2026-04-05 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_rescue_video_url_alter_animal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='health_status',
            field=models.CharField(choices=[('GOOD', 'Buen estado'), ('TREATMENT', 'En tratamiento'), ('CRITICAL', 'Estado crítico'), ('RECOVERED', 'Recuperado')], default='GOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='provenance',
            field=models.CharField(blank=True, help_text='Lugar de procedencia/rescate', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='rescue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('MALE', 'Macho'), ('FEMALE', 'Hembra'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='animalcontentfolder',
            name='species',
            field=models.ForeignKey(blank=True, help_text='Vincula esta carpeta a toda una especie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='animals.species'),
        ),
        migrations.AlterField(
            model_name='animalcontentfolder',
            name='animal',
            field=models.ForeignKey(blank=True, help_text='Dejar vacío para contenido general del Rancho o vinculado a especie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='animals.animal'),
        ),
    ]
