# Generated by Django 6.0.2 on 2026-04-05 22:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_birth_date_animal_health_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='rescue_video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sube un archivo de video directamente a Cloudinary', max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='rescue_video_url',
            field=models.URLField(blank=True, help_text='O pega un link externo (YouTube/Vimeo)', null=True),
        ),
    ]
