# Generated by Django 6.0.2 on 2026-04-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_animal_rescue_video_alter_animal_rescue_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='provenance',
            field=models.TextField(blank=True, help_text='Lugar de procedencia/rescate', null=True),
        ),
    ]
