# Generated by Django 6.0.2 on 2026-03-20 23:33

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_breed_species_remove_animal_type_animal_breed_and_more'),
        ('sponsorship', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RanchUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('min_tier_level', models.IntegerField(default=0, help_text='Minimum level to view this update. 0 for public.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=0, help_text='Higher level means more access')),
                ('type', models.CharField(choices=[('DONATION', 'One-time Donation'), ('SUBSCRIPTION', 'Monthly Subscription')], default='SUBSCRIPTION', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in pesos', max_digits=10)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sponsorship',
            old_name='monthly_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='animal',
            field=models.ForeignKey(blank=True, help_text='Leave blank for general ranch support', null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animal'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sponsorship.sponsorshiptier'),
        ),
    ]
