# Generated by Django 6.0.2 on 2026-03-21 18:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0003_ranchupdate_sponsorshiptier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiptier',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
