# Generated by Django 6.0.2 on 2026-04-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0004_sponsorshiptier_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Mensual'), ('ANNUAL', 'Anual')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='sponsorshiptier',
            name='price_annual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in pesos per year (e.g. Price * 10)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sponsorshiptier',
            name='stripe_price_id_annual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorshiptier',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in pesos per month', max_digits=10),
        ),
    ]
