# Generated by Django 6.0.2 on 2026-04-06 04:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0005_sponsorship_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranchupdate',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
