# Generated by Django 6.0.2 on 2026-04-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0006_alter_ranchupdate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiptier',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this tier from the frontend.'),
        ),
    ]
