# Generated by Django 6.0.2 on 2026-04-08 03:47

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0007_sponsorshiptier_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranchupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='ranchupdate',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Who wrote this update', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ranchupdate',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Main featured image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='RanchUpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='sponsorship.ranchupdate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
