# Generated by Django 6.0.2 on 2026-04-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0008_alter_ranchupdate_options_ranchupdate_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RanchUpdateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ranchupdate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='updates', to='sponsorship.ranchupdatetag'),
        ),
    ]
