# Generated by Django 6.0.2 on 2026-03-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='title',
            field=models.CharField(blank=True, help_text='Ej. Fundador, Coordinador', max_length=100),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
