# Generated by Django 6.0.2 on 2026-03-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('GRAMS', 'Gramos'), ('KILOS', 'Kilos'), ('LITERS', 'Litros'), ('PIECE', 'Pieza')], default='PIECE', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
