# Generated by Django 6.0.2 on 2026-08-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='ID del precio en Stripe', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='ID del producto en Stripe', max_length=255, null=True),
        ),
    ]
